pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        flatDir {
            // Dùng File để lấy đường dẫn tuyệt đối từ gốc dự án
            dirs new File(rootDir, 'noninterruptive_lib/libs')
        }
        maven {
            url 'https://jitpack.io'
        }
    }
}

rootProject.name = "AmazicLibrary"
include ':app'
include ':mylibrary'
include ':customevent'
include ':sdk'
include ':noninterruptive_lib'
