//configurations.maybeCreate("default")
//artifacts.add("default", file('noninterruptive-release.aar'))

plugins {
    id 'com.android.library'
}

android {
    namespace 'com.amazic.noninterruptive' // Đặt tên bất kỳ theo chuẩn package
    compileSdk 35 // Khớp với bản compileSdk của mylibrary

    defaultConfig {
        minSdk 21
    }
    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }
}
tasks.whenTaskAdded { task ->
    if (task.name.contains("bundleReleaseLocalLintAar")) {
        task.enabled = false
    }
}

dependencies {
    // Nhúng file AAR vào module này
    api files('noninterruptive-release.aar')
}